---
title: An R Markdown document converted from "resources/functions_conditionals.ipynb"
output: html_document
---

# Assignment: Python Functions & Conditionals

KATE expects your code to define variables with specific names that correspond to certain things we are interested in.

KATE will run your notebook from top to bottom and check the latest value of those variables, so make sure you don't overwrite them.

* Remember to uncomment the line assigning the variable to your answer and don't change the variable or function names.
* Use copies of the original or previous DataFrames to make sure you do not overwrite them by mistake.

You will find instructions below about how to define each variable.

Once you're happy with your code, upload your notebook to KATE to check your feedback.

The assignment will require you to define functions and then use those functions to solve problems with some datasets.  

Please be sure to **use the function and variable names as specified**, and submit your notebook to KATE for feedback.

### Distance and speed conversions

We discover that 1 mile is equivalent to `1.61` kilometres.

Create a function called `km` with a single parameter called `miles`, (which you can assume will always be a valid number) and returns the equivalent number of kilometres, using the `1.61` value to make the conversion.

```{python}
def km(miles):
    return miles * 1.61

```

Uncomment the following cells to see if your function works as expected:

```{python}
km(85)
```

Use your `km` function as part of your working to calculate the total kilometres covered in the journeys in the list `journeys_miles` defined above. Assign the result to a variable called `journeys_km`:

```{python}
journeys_miles = [1.2, 5.3, 2.7, 8.2]

journeys_km = sum(list(map(km, journeys_miles)))
```

Once you have implememented the preceding code, uncomment the following cell to show the value of `journeys_km`:

```{python}
journeys_km
```

Create a function called `over_kmph_limit` which takes two parameters:
- `mph_speed`, representing the speed of a car in miles per hour
- `kmph_limit`, representing the speed limit in kilometres per hour

The function should return `True` if the car is exceeding the speed limit, and `False` otherwise. You can assume that the input values will always be single positive numerical values.

```{python}
def over_kmph_limit(mph_speed, kmph_limit):
    if km(mph_speed) > kmph_limit:
        out = True
    else:
        out = False
    return out
```

Once you have implemented the function, uncomment the following cells and see if the statements evaluate as you expect:

```{python}
over_kmph_limit(30, 40)
```

```{python}
over_kmph_limit(30, 50)
```

There are of course 1000 metres in a kilometre, and 3600 seconds in an hour.

Create a function called `ms` which takes a single parameter called `kmph`, and returns the equivalent value in metres per second.

You can assume that any argument for `kmph` will be numerical, but if it is negative (i.e. `< 0`), you should instead return the string `'Please enter a positive value.'` Be sure that this string is formatted exactly as given here, i.e. including a full stop at the end.

```{python}
def ms(kmph):
    if kmph < 0:
        out = "Please enter a positive value."
    else:
        out = kmph / 3.6
    return out
```

Once you have implemented your `ms` function, you can uncomment the following cell and run it:

```{python}
ms(156)
```

### Finding entries based on criteria

```{python}
people = [('John', 36, 'M'), ('Rachel', 24, 'F'), ('Deardrie', 78, 'F'), 
          ('Ahmed', 17, 'M'), ('Sienna', 14, 'F')]
```

Create a function called `adults` with a single parameter called `members`, which takes a list of tuples in the format given above (`name`, `age`, `gender`), and returns a list of names (the names only) of those who are aged 18 or over.

```{python}
def adults(members):
    names = []
    for name, age, sex in members:
        if age >= 18:
            names.append(name)
    return names
```

Uncomment the following cell to see if the code below evaluates as you would expect:

```{python}
adults(people)
```

Create a function called `average_age` which takes two parameters:

- `members`, a list of tuples in the same format as `people` above 
- `gender`, a text string such as (but not limited to) `'M'` or `'F'`.

It should return the average age of entries in `members` whose gender matches the argument given for `gender`.

If no matches are found, return the string `'No matches found.'` 

As before, ensure this string is formatted exactly as given here.

```{python}
def average_age(members, gender):
    ages = []
    for name, age, g in members:
        if g == gender:
            ages.append(age)
    if len(ages) == 0:
        out = 'No matches found.'
    else:
        out = sum(ages) / len(ages)
    return out
        
        
```

Uncomment the following cells to seee if your function works as expected:

```{python}
average_age(people, 'M')
```

```{python}

average_age(people, 'Z')
```

Create a function called `member_details`, with two parameters:

- a list of tuples, in the same format as `people` above
- a string, representing the name of one of the entries

You can choose any name for the parameters, but avoid using variables defined elsewhere in the notebook.

The function should return a dictionary with two keys, `age` and `gender`, with the values being those from the tuple which contains the name passed as the second argument to the function. If the name isn't found in the list of tuples, return [`None`](https://www.w3schools.com/python/ref_keyword_none.asp).

```{python}
def member_details(persons, nem):
    out = {}
    for name, age, gender in persons:
        if name == nem:
            out = {'age': age, 'gender': gender}
    if len(out) == 0:
        out = None
        
    return out
```

Call your `member_details` function using `people` and `'Ahmed'` as the arguments, and assign the result to `ahmed_details`.

```{python}
ahmed_details = member_details(persons = people, nem = 'Ahmed')
```

Create a function called `is_member` which takes two arguments:
    
- a list of tuples, in the same format as `people` above (with the name as the first element in each)
- a string, representing a name to be checked whether it is in the list

The function should itself call the `member_details` function you defined earlier to determine whether there is a match; `is_member` should return `True` if there is, and `False` otherwise.

```{python}
def is_member(people, nem):
    if (member_details(people, nem)) is None:
        return False
    else:
        return True
```

Create a function called `check_group` which has two arguments:

- a list of names representing existing members (just a list, not tuples as previously)
- a list of names representing visitors (who may or may not be members)

The function should return a string in the format `'Member present: {person}.'` (ensure it matches this exactly), where `{person}` is replaced by the first name in the visitors to be identified as a member. 

If no member is found, return `'No members.`'

```{python}
def check_group(member_list, visitor_list):
    out = 'No members.'
    for member in member_list:
        for visitor in visitor_list:
            if member == visitor:
                out = 'Member present: ' + member +'.'
            
    return out
```

```{python}
members = ['Alex', 'Danny', 'Kieran', 'Zoe', 'Caroline']
visitors = ['Scott', 'Helen', 'Raj', 'Danny']
```

See if your function works as expected by running the cell below:

```{python}
check_group(members, visitors)
```

Create a function called `guests` which has three parameters:
- a list of strings representing existing members
- a list of strings representing new members
- a list of strings representing visitors

The function should return a list of visitors who are neither existing nor new members. If there are none, return [`None`](https://www.w3schools.com/python/ref_keyword_none.asp).

```{python}
def guests(existing_members, signups, visitors):
    mem = existing_members.copy()
    mem.extend(signups)
    vislist = list(set(visitors).difference(mem))
    if len(vislist) == 0:
        return None
    else:
        return vislist
```

Uncomment and run the cell below and see whether your function works as expected:

```{python}
signups = ['Helen', 'Scott']
guests(members, signups, visitors)
```

