---
title: "Udemy Assignments"
author: "Steve Crawshaw"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(tidyverse)
use_condaenv("ds01")

```

# Assignment 17
Sort this list of tuples by the first element
```{python 'assignment_17'}
x = [(3, "Santiano"), (1, "Vito"), (4, "Fredo"), (10, "Tessio"), (7, "Connie") \
,(9, "clemenza"), (2, "Michael")]

# function returns the 1st element of each tuple
def sort_order(each_element):
    return each_element[0]
# that element is used as the key for the sort
x.sort(key = sort_order)
x

```

```{r 'assignment_17'}
# The conversion from py to r auto sorts the list by the first element(!)
xr <- py$x
# but if we want to sort manually
install.packages("rlist")
library(rlist)
# could sort in reverse with rev and rlist::list.sort
xrsorted <- rev(list.sort(xr, 1))
```


```{python 'assignment_18'}
def f1(x = []):
    x.append(len(x))
    return x

f1([2,6,7])

f1(['hello', 2.3, 1, "python"])
f1([]) #gives zero
f1()
f1()
f1()
f1([])

# because of dunder - f1.__defaults__ is set to empty list only when the function is first defined. so subsequent calls can override, because x ( a mutable list in this case) is changed in the body of the function and that affects the value of x as a default parameter in the function arguments.

def f1(x = []):
    x.append(len(x))
    return x


f1.__defaults__ # the default function parameter(s)

f1()

# make a change to the code

def f1(x = None):
    if x == None: x = [] # forces x assignment of [] when x == None
    x.append(len(x))
    return x

# KEY POINT - using a mutable object as a default in function arguments can cause unintended behaviour due to dunder defaults being set unintentionally when no parameters are passed. Need to deal with this explicitly, either in the code or by setting immutable objects as defaults.


```

```{r "assignment_18"}

# R doesn't do this!
f1 <- function(x = list()){
    x = append(x, length(x))
    return(x)
    }

f1(list(1, 3, 6))

f1()

```

```{python "assignment_19"}

def age_at_birth(man, woman, child):
    error = False
    if man - child < 18 or woman - child < 18:
        print("Too young")
        error = True
    elif man - child > 60  or woman - child > 60:
        print("Too old")
        error = true
    elif ~error:
        man_age_when_born = man - child
        woman_age_when_born = woman - child
        
        return f'The man was {man_age_when_born} and the woman was \
        {woman_age_when_born} when the child was born'

age_at_birth(man = 40, woman = 23, child = 10)

```

```{r "assignment_19"}

age_at_birth <- function(man, woman, child){
    error <- FALSE
    if (man - child < 18 | woman - child < 18){
        print("Too young")
        error = TRUE
    } else if(man - child > 60  | woman - child > 60) {
        print("Too old")
        error = TRUE
    } else if(!error){
        man_age_when_born = man - child
        woman_age_when_born = woman - child
        
        return(glue("The man was {man_age_when_born} and the woman was {woman_age_when_born} when the child was born"))
    }
        
}

age_at_birth(man = 40, woman = 45, child = 10)
```


```{python "assignment_20"}
def num_arith(x, y):
    sm = x + y
    diff = x - y
    prod = x * y
    div = x / y
    print(f'sum = {sm}, difference = {diff}, product = {prod}, division = {div}')
num_arith(9, 7)


# with lambda as a tuple

n_arith = lambda x, y: (x+y, x-y, x*y, x/y)
n_arith(7, 9)

```

```{r "assignment_20"}
# with native lambda notation from R 4.1
arith <- \(x, y) c(x+y, x-y, x*y, x/y)
arith(9, 7)
```

swap the keys and values in a dictionary
```{python "assigment_21"}

def swap(my_dict):
    swapped_dict = {}
    for k, v in my_dict.items():
        swapped_dict[v] = k
    return swapped_dict

x = {"one":1, "two":2, "three":3}

swap(x)

x.items()

```

```{r "assignment_21"}

x <- c("one" = 1, "two" = 2, "three" = 3)

swap <- function(x){
    vals <- unname(x)
    keys <- names(x)
    names(keys) <- vals
    return(keys)
}

swap(x)
```

Assignment 22 - write a function to return the max value in a list without using max()

```{python "assignment_22"}
# my solution
def max_value(alist):
    alist.sort(reverse = True) # default inplace = True!
    return alist[0]

alist = [1, 6, 90, 120, 3]
max_value(alist)

# Udemy solution

def max_l(my_list):
    my_max = float("-inf") # a very small number to initialise
    for e in my_list:
        if e > my_max:
            my_max = e # capture the biggest number in my_max
    return my_max

max_l(alist)

```

```{r "assignment_22"}

numvec <- c(1, 4, 7, 34, 2, 5)
rev(sort(numvec))[1]
# using a for loop
findmax <- function(numvec){
    my_max = -Inf
    for(each in numvec){
        if(each > my_max){
            my_max <-  each
        }
 }
 return(my_max)
}
findmax(numvec)
```


Create a function to count the number of upper and lower case characters in a string
```{python "assignment_23"}

def count_case(astring):
    u = int(0)
    l = int(0)
    for i in astring:
        if i.upper() == i: # can use .isupper()
            u += 1
        elif i.islower():
            l += 1
    return (u, l)
        
astring = "asdBB,LLLLLG"

count_case(astring)

```

```{r "assignment_23"}

astring <-  "asdBB,LLLLLG"

?toupper

```

